### ISSUE TITLE
react-hooks

### ISSUE THREAD

**Issue by dkishmareishvili** [laststance/vite-react-ts-extended#19]
Thanks a lot for sharing this Repository!
Please update 
 "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:react-hooks/recommended"
  ],

**Comment by ryota-murakami** [comment]
@dkishmareishvili Thank you for your feedback.  
This project settings comings from my frequency setup, so sometimes there is pretty opinionated one.  

For the reason, I don't use to `"react-hook/exhaustive-deps"` lint rule so I only enabled `"react-hooks/rules-of-hooks" "error"` by hand in `.eslintrc` over `"plugin:react-hooks/recommended"`  because ignore rules-of-hooks cause application crash.  

When I write something code with `useEffect()` that should fire 🔥  only first component render.(Similar ClassComponent's `componentDidMount` behavior.)  
For example this implementation.  

```js
const foo = () => {...};
useEffect(() => {
    foo();
  }, [])
  ```

I expected `foo()` execute only once at first render timing. 
but `"react-hook/exhaustive-deps"` rule says `React Hook useEffect has a missing dependency: 'foo'.`
Obey this rule will cause unintended or unexpected behavior(this case might be infinite loop).  

I have an annoying to write `// eslint-disable-next-line react-hook/exhaustive-deps` when I create `componentDidMount()` logic every time.  

Therefore don't use "plugin:react-hooks/recommended" eslint setting is intentional.  
Please modify all settings feel free, thank you!
